# Usa una imagen de Node.js para construir la aplicación
FROM node:19 as builder

WORKDIR /app

# Copia los archivos necesarios y construye la aplicación
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# Usa una imagen más ligera para servir la aplicación
FROM nginx:alpine

# Copia los archivos construidos desde la imagen anterior
COPY --from=builder /app/dist /usr/share/nginx/html

# Configura Nginx para servir la aplicación
COPY nginx.conf /etc/nginx/nginx.conf

# Expone el puerto 80
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
