#Download base image ubuntu 16.04
FROM node:14.17.6

#Mainterner
LABEL MAINTAINER = "CUNOC"


# install dependencies
WORKDIR /var/www/html/api
COPY package.json package-lock.json* ./
RUN npm cache clean --force && npm install

# Copy .env file to the image
COPY .env .env

# copy app source to image _after_ npm install so that
# application code changes don't bust the docker cache of npm install step
COPY . /var/www/html/api

# Install TypeScript globally
RUN npm install -g typescript

# TypeScript
RUN tsc

RUN npm run seed
# set application PORT and expose docker PORT, 80 is what Elastic Beanstalk expects
ENV PORT 3016
EXPOSE 3016

CMD [ "npm", "run", "start" ]
